version: "2"

services:
  roundcubemail:
    build: ./
    container_name: roundcubemail
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    ports:
      - 9000:9000
    volumes:
      - /srv/roundcube/html:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb # same as pgsql container name
      - ROUNDCUBEMAIL_DB_NAME=roundcube # same as pgsql POSTGRES_DB env name
      - ROUNDCUBEMAIL_DB_USER=roundcube # same as pgsql POSTGRES_USER env name
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube # same as pgsql POSTGRES_PASSWORD env name

  roundcubedb:
    image: postgres:alpine
    container_name: roundcubedb
    ports:
      - 5432:5432
    volumes:
      - /srv/roundcube/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER=roundcube
      - POSTGRES_PASSWORD=roundcube

  roundcubenginx:
    image: nginx:latest
    container_name: roundcubenginx
    ports:
      - 80:80
    depends_on:
      - roundcubemail
    links:
      - roundcubemail
    volumes:
      - /srv/roundcube/html:/var/www/html
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
