name: Build Docker image

on: [push]

jobs:
  build-variants:
    name: Build image variants
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variants: ["apache", "fpm", "fpm-alpine"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get docker hub username
        id: creds
        run: echo '::set-output name=username::${{ secrets.DOCKER_PULL_USERNAME }}'
      - name: Login to Docker Hub
        if: steps.creds.outputs.username != ''
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_PULL_USERNAME }}
          password: ${{ secrets.DOCKER_PULL_PASSWORD }}
      - name: Build image variant "${{ matrix.variants }}"
        run: cd ${{ matrix.variants }} && docker build ./
